//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NArgs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NArgs.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments not processed.
        /// </summary>
        internal static string ArgumentsNotProcessedErrorMessage {
            get {
                return ResourceManager.GetString("ArgumentsNotProcessedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command with that given name does not exist.
        /// </summary>
        internal static string CommandDoesNotExistErrorMessage {
            get {
                return ResourceManager.GetString("CommandDoesNotExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMANDS.
        /// </summary>
        internal static string CommandsCapitalizedName {
            get {
                return ResourceManager.GetString("CommandsCapitalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required parameter value.
        /// </summary>
        internal static string MissingRequiredParameterValueErrorMessage {
            get {
                return ResourceManager.GetString("MissingRequiredParameterValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple commands used.
        /// </summary>
        internal static string MultipleCommandsUsedErrorMessage {
            get {
                return ResourceManager.GetString("MultipleCommandsUsedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string NotApplicableValue {
            get {
                return ResourceManager.GetString("NotApplicableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string NotAvailableShortName {
            get {
                return ResourceManager.GetString("NotAvailableShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option with that given name does not exist.
        /// </summary>
        internal static string OptionDoesNotExistErrorMessage {
            get {
                return ResourceManager.GetString("OptionDoesNotExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &quot;{0}&quot; is missing a required value.
        /// </summary>
        internal static string OptionIsMissingRequiredValueFormatErrorMessage {
            get {
                return ResourceManager.GetString("OptionIsMissingRequiredValueFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        internal static string OptionsCapitalizedName {
            get {
                return ResourceManager.GetString("OptionsCapitalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option.
        /// </summary>
        internal static string OptionUsageTypeDisplayName {
            get {
                return ResourceManager.GetString("OptionUsageTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARAMETERS.
        /// </summary>
        internal static string ParametersCapitalizedName {
            get {
                return ResourceManager.GetString("ParametersCapitalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters must precede any options.
        /// </summary>
        internal static string ParametersMustPrecedeAnyOptionsErrorMessage {
            get {
                return ResourceManager.GetString("ParametersMustPrecedeAnyOptionsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters not allowed beside commands.
        /// </summary>
        internal static string ParametersNotAllowedBesideCommandsErrorMessage {
            get {
                return ResourceManager.GetString("ParametersNotAllowedBesideCommandsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property does not have an option attribute.
        /// </summary>
        internal static string PropertyDoesNotHaveAnOptionAttributeErrorMessage {
            get {
                return ResourceManager.GetString("PropertyDoesNotHaveAnOptionAttributeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyService not initialized.
        /// </summary>
        internal static string PropertyServiceNotInitializedErrorMessage {
            get {
                return ResourceManager.GetString("PropertyServiceNotInitializedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property without value requires type &quot;System.Boolean&quot;.
        /// </summary>
        internal static string PropertyWithoutValueRequiresTypeBooleanErrorMessage {
            get {
                return ResourceManager.GetString("PropertyWithoutValueRequiresTypeBooleanErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYNTAX.
        /// </summary>
        internal static string SyntaxCapitalizedName {
            get {
                return ResourceManager.GetString("SyntaxCapitalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; is invalid for option &quot;{1}&quot;.
        /// </summary>
        internal static string ValueIsInvalidForOptionFormatErrorMessage {
            get {
                return ResourceManager.GetString("ValueIsInvalidForOptionFormatErrorMessage", resourceCulture);
            }
        }
    }
}
